### PR TITLE
Fix to ArbitratedScratchpad.h when Numbanks=1

### PR DESCRIPTION
**Pull request by ttambe**
Pull request addressing issue #6 when `Numbanks` = 1

### CODE REVIEW

**Comment by ben-k** [comment]
Looks good to me.  Could you squash the two commits into one?  Then I'll merge this once it clears our internal CI.

**Comment by ttambe** [comment]
Done.

**Comment by ben-k** [comment]
Sorry, one additional nit - can you clean up the commit message to remove the second line, "small additional fix to ArbitratedScratchpad.h when Numbanks=1"?

**Comment by ttambe** [comment]
No worries. Done.

**Pull request merged**
